openapi: 3.0.3
info:
  title: Stock Boost Management API
  description: API for managing stock price boosts with user authentication
  version: 1.0.0
  contact:
    name: Stock Boost Team
    
servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://stock-boost.vercel.app/api
    description: Production server

paths:
  /auth/login:
    post:
      summary: Authenticate user with username and password
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
                example: "session=eyJhbGciOiJIUzI1NiJ9...; Path=/; HttpOnly; Secure; SameSite=Lax"
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      summary: Logout current user and clear session
      tags: [Authentication]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          headers:
            Set-Cookie:
              description: Clear session cookie
              schema:
                type: string
                example: "session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"

  /auth/me:
    get:
      summary: Get current authenticated user
      tags: [Authentication]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /boosts:
    get:
      summary: Get stock boosts (active or historical)
      tags: [Stock Boosts]
      security:
        - sessionAuth: []
      parameters:
        - name: type
          in: query
          description: Type of boosts to retrieve
          schema:
            type: string
            enum: [active, historical]
            default: active
        - name: page
          in: query
          description: Page number for pagination (historical only)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Items per page (historical only)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sku
          in: query
          description: Filter by SKU
          schema:
            type: string
      responses:
        '200':
          description: List of stock boosts
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BoostListResponse'
                  - $ref: '#/components/schemas/PaginatedBoostResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new stock boost
      tags: [Stock Boosts]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBoostRequest'
      responses:
        '201':
          description: Stock boost created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoostResponse'
        '400':
          description: Invalid request data or business rule violation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /boosts/{id}:
    delete:
      summary: Deactivate a stock boost
      tags: [Stock Boosts]
      security:
        - sessionAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Boost ID to deactivate
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeactivateBoostRequest'
      responses:
        '200':
          description: Boost deactivated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoostResponse'
        '404':
          description: Boost not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid request or boost already inactive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /skus/search:
    get:
      summary: Search for SKUs
      tags: [SKUs]
      security:
        - sessionAuth: []
      parameters:
        - name: q
          in: query
          required: true
          description: Search query for SKU, name, or category
          schema:
            type: string
            minLength: 1
            maxLength: 100
        - name: limit
          in: query
          description: Maximum number of results
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: List of matching SKUs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuSearchResponse'
        '400':
          description: Invalid search query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # Request Schemas
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[A-Za-z0-9_]+$'
          example: "admin"
        password:
          type: string
          minLength: 8
          maxLength: 100
          example: "password123"

    CreateBoostRequest:
      type: object
      required:
        - sku
        - amount
      properties:
        sku:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[A-Za-z0-9_-]+$'
          example: "LAPTOP-001"
        amount:
          type: number
          minimum: 0.01
          maximum: 999999.99
          multipleOf: 0.01
          example: 50.00
        expiresAt:
          type: string
          format: date-time
          description: Optional expiration date
          example: "2025-12-01T00:00:00Z"

    DeactivateBoostRequest:
      type: object
      required:
        - reason
      properties:
        reason:
          type: string
          enum: [manual]
          description: Reason for deactivation
          example: "manual"

    # Response Schemas
    AuthResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/User'

    UserResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/User'

    BoostResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/StockBoost'

    BoostListResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/StockBoost'

    PaginatedBoostResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/StockBoost'
        pagination:
          $ref: '#/components/schemas/PaginationInfo'

    SkuSearchResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Sku'

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operation completed successfully"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Invalid credentials"
        details:
          type: object
          description: Additional error details (validation errors, etc.)

    # Entity Schemas
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: "admin"
        createdAt:
          type: string
          format: date-time
          example: "2025-01-01T00:00:00Z"
        lastLoginAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-11-03T10:30:00Z"

    StockBoost:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "boost-123e4567-e89b-12d3-a456-426614174000"
        sku:
          type: string
          example: "LAPTOP-001"
        amount:
          type: number
          format: decimal
          example: 50.00
        status:
          type: string
          enum: [active, inactive]
          example: "active"
        createdAt:
          type: string
          format: date-time
          example: "2025-11-01T00:00:00Z"
        createdBy:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        deactivatedAt:
          type: string
          format: date-time
          nullable: true
          example: null
        deactivationReason:
          type: string
          enum: [expired, manual]
          nullable: true
          example: null
        expiresAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-12-01T00:00:00Z"

    Sku:
      type: object
      properties:
        sku:
          type: string
          example: "LAPTOP-001"
        name:
          type: string
          example: "Gaming Laptop Pro"
        category:
          type: string
          example: "Electronics"
        isActive:
          type: boolean
          example: true

    PaginationInfo:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        total:
          type: integer
          example: 100
        totalPages:
          type: integer
          example: 5

  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: session
      description: Session-based authentication using secure cookies

security:
  - sessionAuth: []

tags:
  - name: Authentication
    description: User authentication and session management
  - name: Stock Boosts
    description: Stock boost creation and management
  - name: SKUs
    description: Product SKU search and validation